### ISSUE TITLE
This project is awesome

### ISSUE THREAD

**Issue by slang25** [hardkoded/playwright-sharp#285]
I just came to say I've been having a play with this, and it rocks! What's the general status, can I help in some way?

**Comment by kblok** [comment]
Hey @slang25!
We are working hard! We have [a project](https://github.com/hardkoded/playwright-sharp/projects/1) to ship v0.10.0. the equivalent of Playwright v0.10.0.

We don't have many "good first issues" yet. We have only one https://github.com/hardkoded/playwright-sharp/issues/272

We also have this console app we need to code https://github.com/hardkoded/playwright-sharp/issues/158

If you want to get deeper, nobody started with WebKit support yet. It's a matter to start with Launcher tests first.

I'm open (and embrace) new contributors, as long as you raise your hand and tell us what you want to work on, and accept our code review :p  

Github sponsors are also open here, so funding is also welcome.

I'm on Playwright's Slack, so you can also reach me out there https://join.slack.com/t/playwright/shared_invite/zt-bn1bdq78-jAUfslSxLGIjf9BxQe4OHA

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
