### ISSUE TITLE
Refactor JSHandle.RemoteObject

### ISSUE THREAD

**Issue by kblok** [hardkoded/playwright-sharp#290]
I think JSHandle.RemoteObject could be a `RemoteObject` instead of an `IRemoteObject`

**Comment by Meir017** [comment]
but we have 2 different implementations in firefox and chromium
why would you need a concrete type here?

**Comment by Meir017** [comment]
this could make sense on the JSHandle and ElementHandle to use the concrete type without the interface

**Comment by kblok** [comment]
Ah that was why...
