### ISSUE TITLE
Firefox: Review ClickTests.ShouldGracefullyFailWhenPageCloses test

### ISSUE THREAD

**Issue by kblok** [hardkoded/playwright-sharp#304]
This seems to be a recurrent issue fail https://github.com/hardkoded/playwright-sharp/runs/575375369#step:4:59

**Comment by Meir017** [comment]
can we close this? we now use `Assert.ThrowsAnyAsync<PlaywrightSharpException>`

**Comment by kblok** [comment]
closed.
