### ISSUE TITLE
Review NetworkIdleTests

### ISSUE THREAD

**Issue by kblok** [hardkoded/playwright-sharp#367]
Those tests are quite instable in CI.

**Comment by Meir017** [comment]
I found an issue here,
in some places we have
```cs
foreach (var watcher in LifecycleWatchers.ToArray())
{
    watcher.On...();
}
```
sometimes `watcher` is null, not sure if the right thing is to change it to `watcher?.On...()` but it could help

**Comment by kblok** [comment]
We could try that. My main concern is whether the bug is that null check or if we have some race condition and we needed to send a message to a disposed watcher. We'll see.
