### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by Meir017** [hardkoded/playwright-sharp#388]
![image](https://user-images.githubusercontent.com/9786571/81820227-00f5ba80-9539-11ea-9fe8-d7d332027a82.png)

see https://github.com/hardkoded/playwright-sharp/runs/668927169

`PlaywrightSharp.Tests.RequestInterception.PageSetRequestInterceptionTests.ShouldWorkWithEqualRequests` is flaky.

in playwright this fixed this in version `v0.12.0`
![image](https://user-images.githubusercontent.com/9786571/81820115-dd327480-9538-11ea-9f4c-a0c1298fb399.png)
see here https://github.com/microsoft/playwright/compare/v0.11.0...v0.12.0#diff-7ff6d7fc2247e88768a12321914b9a2bL247-R259

I think it's worth it fixing this now

**Comment by Meir017** [comment]
@kblok what do you think?

**Comment by kblok** [comment]
@Meir017 yeah, let's do it.
