### ISSUE TITLE
BrowserFetcher CLI 

### ISSUE THREAD

**Issue by kblok** [hardkoded/playwright-sharp#411]
Let's build a dotnet CLI tool to install browsers

**Comment by Meir017** [comment]
I was thinking of
```ps1
browser-fetcher install -browserType [-version] [-location] [-host]
```
the cli will only download the browser if it doesn't exist locally
- `browserType` is one of `chromium`, `firefox` or `webkit`
- `version` is an optional argument, if missing we'll download the lastest version
- `location` custom path to save to
- `host` custom host to download from

**Comment by kblok** [comment]
Yes. The idea is to create a [dotnet tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools) and we should have the playwright-sharp brand. I think it could be `playwrightsharp add-browser` we could also have stuff like `list-browsers`, `remove-browsers`.

This is a low priority issue BTW.
