### ISSUE TITLE
Pass firefox/launcher.spec.js on WebKit

### ISSUE THREAD

**Issue by kblok** [hardkoded/playwright-sharp#553]
Let's implement these tests on WebKit.This PR might help https://github.com/kblok/playwright/pull/2/files.

**Comment by Meir017** [comment]
this should probably be renamed to `Pass launcher.spec.js on WebKit`

**Comment by kblok** [comment]
@Meir017 as we agreed on not adding traits when the test is completely ignored, we could close this issue. What do you think?

**Comment by Meir017** [comment]
I agree.
I meant that the title of this issue is confusing. it's both firefox and WebKit ;)
