### ISSUE TITLE
Playwright Sharp multithread problems

### ISSUE THREAD

**Issue by abraaocaldas** [hardkoded/playwright-sharp#703]
Hello, I'm using the Firefox Browser with playwright-sharp 

If I open multiple pages using the same browser instance and use the EvaluateAsync on the pages they only return when all EvaluateAsyncs are evaluated.

I can use it just fine on pupetteer-sharp, but not on playwright :/

**Comment by kblok** [comment]
Hey @abraaocaldas. I'm doing a massive refactor on the way to v1.1.1. Do you want to see if building the main branch will work for you?

**Comment by abraaocaldas** [comment]
Sure! I will build and check soon.

**Comment by abraaocaldas** [comment]
I using the code from commit f67ed0f5

There is some strange behaviors :

- When I launch a browser.NewPageAsync(), it opens another browser instance instead a new tab like the previous version
- Seems like if you try to open a NewPageAsync from another thread (usingthe browser reference) the result of the operation never returns neither the timeout is triggered
- The function EvaluateOnNewDocumentAsync was replaced?

**Comment by kblok** [comment]
>When I launch a browser.NewPageAsync(), it opens another browser instance instead a new tab like the previous version
browser.NewPageAsync now creates a new context (window) and gives you a new tab there. If you want to re-use the initial context you can do `browser.Context[0].NewPageAsync().

>Seems like if you try to open a NewPageAsync from another thread (usingthe browser reference) the result of the operation never returns neither the timeout is triggered

I'm super interested on this one. Would you mind sharing some code with me? You could send it by email if you don't feel comfortable sharing that here.

>The function EvaluateOnNewDocumentAsync was replaced?
AddInitScript :)

**Comment by abraaocaldas** [comment]
I took the liberty your demo code :) when you need to evaluate something on the page and there are multiple instances of the same page, it will block until the evaluation happens on all pages, this is the intended behavior?

Sample code :

```
static async Task Main(string[] args)
        {
            await Playwright.InstallAsync().ConfigureAwait(false);
            var playwright = await Playwright.CreateAsync();
            var chromium = playwright.Chromium;
            var browser = await chromium.LaunchAsync(new LaunchOptions { Headless = false });            

            Parallel.For(1, 100, new ParallelOptions { MaxDegreeOfParallelism = 10 }, i =>
              {
                  var page = browser.NewPageAsync().Result;

                  page.GoToAsync("https://news.google.com").Wait();
                  var result = page.EvaluateAsync("window.content").Result;
                  page.CloseAsync().Wait();
              });

            Console.ReadLine();
        }
```

**Comment by kblok** [comment]
@abraaocaldas, the problem there is that `wait` and `result` are blockers (this is a good reading https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html)

You should use async/await across the board. You should be able to do that even with `Parallel.For`.

**Comment by abraaocaldas** [comment]
I understand your remark about `wait` and `result`, but  `Parallel.for` should be working fine as long as the threads do not wait for a result of another thread. If you do the exact same thing on  puppeteer-sharp you will see that even using `wait`  or `result` will give you a proper execution it will open -> evaluate -> close tabs regardless of another tabs/instances.

**Comment by kblok** [comment]
The problem is that .NET uses the same objects for two different things: Parallelism and Asyncronysm. And you are using both at the same time, so that might be confusing. `wait` and `result` blocks asynchronous tasks, you shouldn't use `.Wait` and `.Result` for async tasks.

With `.Result` you are locking the current thread, and nothing guarantees that async task will be resolved in another thread.

If there is something to be improved in the code, I would gladly review a PR, but I strongly believe that async/await is the way to go.

**Comment by abraaocaldas** [comment]
I still cannot open a new tab still giving me the exception :

``One or more errors occurred. (Please use Browser.NewContextAsync())``

**Comment by kblok** [comment]
If you call `browser.NewPageAsync()`. Playwright will create a new context and a new page in that context. It won't allow you to add new pages to that context.

If you want to create a many tabs in a context, you should first create the context and then create pages from it:

```cs 
var context  = await browser.NewContext();
var page1 = await context.NewPage();
var page2 = await context.NewPage();
```

Let me know if that helps :)

**Comment by abraaocaldas** [comment]
> 
> 
> If you call `browser.NewPageAsync()`. Playwright will create a new context and a new page in that context. It won't allow you to add new pages to that context.
> 
> If you want to create a many tabs in a context, you should first create the context and then create pages from it:
> 
> ```cs
> var context  = await browser.NewContext();
> var page1 = await context.NewPage();
> var page2 = await context.NewPage();
> ```
> 
> Let me know if that helps :)

I will close this issue, since it diverted to another topic, I will create a new one regarding this issue.
