### ISSUE TITLE
The link to Project Site on the NuGet Gallery is broken

### ISSUE THREAD

**Issue by hlaueriksson** [hardkoded/playwright-sharp#849]
In the [NuGet Gallery page](https://www.nuget.org/packages/PlaywrightSharp/) of `PlaywrightSharp` version `0.111.2` and `0.111.1`, the link to Project Site is broken.

It points to `https://github.com/hardkodedinstallasy/playwright-sharp`.
For some reason `installasy` is included in the URL.

(The page for version `0.111.0` does not have this issue)

The csproj file looks good to me; https://github.com/hardkoded/playwright-sharp/blob/master/src/PlaywrightSharp/PlaywrightSharp.csproj#L12

So, where does the `installasy` come from!? 🤷‍♂️

**Comment by slang25** [comment]
It was fixed, I came to fix the same thing a few days back and it was already fixed in master

**Comment by kblok** [comment]
It was already fixed, folks. That's what happens when you want to ship a new package on Sunday 😂
