### ISSUE TITLE
Playwright on mac not working - 0.111.2 or master

### ISSUE THREAD

**Issue by skyflyer** [hardkoded/playwright-sharp#856]
First of all, thank you for the effort in porting Playwright to C#. Kudos!

What follows, is my digging through the code and ... (spoiler alert!) making it work.

I've been using version 0.10.3 so far and tried to upgrade to 0.111.2 or even `master`, but I'm kind-of stuck. :(

The 0.111.2 fails with permission denied, as it fails to execute `playwright-driver-macos` process, but there is already a fix for that.

The master fails with the error where it tries to download a hardcoded version of the browser and fails. I changed the browsers.json file to this content (cue taken from the original Playwright repo):

<details><summary>browsers.json</summary>
```json
{
  "comment": "Do not edit this file, use utils/roll_browser.js",
  "browsers": [
    {
      "name": "chromium",
      "revision": "799411",
      "download": true
    },
    {
      "name": "firefox",
      "revision": "1169",
      "download": true
    },
    {
      "name": "webkit",
      "revision": "1341",
      "download": true
    }
  ]
}
```
</details>

When `playwright-driver-macos` executes, it tries to download https://playwright.azureedge.net/builds/chromium/792639.1/chromium-mac.zip which fails:

<details>
<summary>UnhandledPromiseRejectionWarning: Error: Download failed: server returned code 404</summary>
Installing playwright
(node:29700) UnhandledPromiseRejectionWarning: Error: Download failed: server returned code 404. URL: https://playwright.azureedge.net/builds/chromium/792639.1/chromium-mac.zip
    at /snapshot/playwright/lib/install/browserFetcher.js:181:27
    at ClientRequest.requestCallback (/snapshot/playwright/lib/install/browserFetcher.js:226:13)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
(node:29700) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29700) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
</details>

I tried to find the source for the driver installer, but I was unable to (where are they?). I then switched to branch `v1.4/update-drivers` which had the updated driver, and... ta-da, it works.

Can you let us know where to find the source for `playwright-driver-macos` for future reference?

Thanks!

PS: eagerly awaiting official 1.4 release.

**Comment by kblok** [comment]
Hey @skyflyer. Thanks for the early support :)

Could you try master again? We are using the latest driver now #855

>Can you let us know where to find the source for playwright-driver-macos for future reference?

The source is playwright. You have to run `./utils/build_driver.sh`

Again, thanks for the support. Looking forward to your feedback.

**Comment by skyflyer** [comment]
Hey @kblok, sorry for a late reply. The `master` branch works now,  yep. Thanks for the info about `build_driver`.
